In [28]:
import numpy as np

a=np.array([[1,3,4,5],[1,3,7,5],[1,23,4,4]])
#accessing the elements
print(a[0][2])
print("dimensions are : ",a.ndim)#no.of axes
#no. of rows and columns
print("no of rows and columns",a.shape)
#elements present in the array
print("elements present in the array",a.itemsize)
#printing the array 
print(a)

4
dimensions are :  2
no of rows and columns (3, 4)
elements present in the array 4
[[ 1  3  4  5]
 [ 1  3  7  5]
 [ 1 23  4  4]]


In [29]:
#printing all ones and zeros
import numpy as np

#printing all  zeros in a arrray
a=np.zeros((3,4))
print(a)
#printing all ones in a array
b=np.ones((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
#printing all the elements in the array as same.using full function
import numpy as np

a=np.full((3,3),34,dtype='int32')
print(a)

[[34 34 34]
 [34 34 34]
 [34 34 34]]


In [3]:
#creating an identity matrix
import numpy as np

a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
import numpy as np

a=np.array([[12,34,4],[1,3,2]])
b=np.repeat(a,3,axis=1)
c=np.repeat(a,3,axis =0)
print("the repeatition along axis 0 :",c)
print("the repeatition along axis 1 :",b)

the repeatition along axis 0 : [[12 34  4]
 [12 34  4]
 [12 34  4]
 [ 1  3  2]
 [ 1  3  2]
 [ 1  3  2]]
the repeatition along axis 1 : [[12 12 12 34 34 34  4  4  4]
 [ 1  1  1  3  3  3  2  2  2]]


In [32]:
#printing the range using numpy
import numpy as np

a=np.arange(5)

print(a)

[0 1 2 3 4]


In [33]:
#concatenation using numpy
import numpy as np

#concatenation
a=np.char.add(['hello ','welcome to'],['akill',' cse'])
print(a)

['hello akill' 'welcome to cse']


In [42]:
#multiplying the string using numpy

import numpy as np

a=np.char.multiply(' hello ',3)
print(a)

 hello  hello  hello 


In [45]:
#making the space in between the string

import numpy as np

a=np.char.center('hello',20,fillchar='*')
print(a)

*******hello********


In [54]:
#using the string functions in numpy
import numpy as np

#capitalize function
a=np.char.capitalize('akill raja')
print(a)
#title function 
a=np.char.title('akill raja')
print("title is :",a)
#lower case function
a=np.char.lower([['HELLO'],["AKILL"]])
print("the lower case is ",a)
#uppercase string function
a=np.char.upper(['akill'])
print("uppercase is: ",a)
#split function
a=np.char.split('hello who are you')
print(a)

Akill raja
title is : Akill Raja
the lower case is  [['hello']
 ['akill']]
uppercase is:  ['AKILL']
['hello', 'who', 'are', 'you']
