In [20]:
#converting single array into multi-array
import numpy as np


a=np.arange(16)
print("the original array is :")
print(a)

b=a.reshape((4,4))
print("the modified array is :")
print(b)

the original array is :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
the modified array is :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [35]:
#converting multi-array into single array
import numpy as np

#getting the range
a=np.arange(9)
print("the original array is :")
print(a)

#reshaping the range array into a matrix form
b=a.reshape((3,3))
print("the modified array is :")
print(b)

#back to single array 
c=b.flatten()
print("the original array is back to form:")
print(c)

#single array format by accessing the flatten in column-major
d=b.flatten(order='f')
print("the accessing the elements in a order :")
print("the modifed array is : ",b)
print(d)

the original array is :
[0 1 2 3 4 5 6 7 8]
the modified array is :
[[0 1 2]
 [3 4 5]
 [6 7 8]]
the original array is back to form:
[0 1 2 3 4 5 6 7 8]
the accessing the elements in a order :
the modifed array is :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 3 6 1 4 7 2 5 8]


In [42]:
#transpose of the array 
import numpy as np


a=np.arange(12).reshape(3,4)
print(a)
print("the transpose of arrar  A : ")
b=np.transpose(a)
print(b)
c=np.rollaxis(b,2,3)
print(c)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
the transpose of arrar  A : 
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
