In [20]:
#converting single array into multi-array
import numpy as np


a=np.arange(16)
print("the original array is :")
print(a)

b=a.reshape((4,4))
print("the modified array is :")
print(b)

the original array is :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
the modified array is :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [24]:
#converting multi-array into single array
import numpy as np


a=np.arange(16)
print("the original array is :")
print(a)

b=a.reshape((4,4))
print("the modified array is :")
print(b)

c=b.flatten()
print("the original array is back to form:")
print(c)

the original array is :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
the modified array is :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
the original array is back to form:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
