In [43]:
# 1. Question.
# np.all --> checks all the element in the array is true otherwise returns false.
# axis = 1 for Rows in the array.
# axis = 0 for columns in the array.
import numpy as np


A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

for i,j in zip(list('ABC'),[A,B,C]):
    print(f"{i}: {np.all(j,axis=0)}")



A: [ True  True  True  True]
B: [ True  True False  True]
C: [ True False False]


In [55]:
# 2. Question
# np.any  --> Tests any value one of the Value is true in the array otherwise returns false.
# checking for both rows and columns.
import numpy as np


A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for i,j in zip(list('ABCD'),[A,B,C,D]):
    print(np.any(j))

False
True
True
True


In [58]:
# 3.question 
# checking for column axis.
import numpy as np


A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for i,j in zip(list('ABCD'),[A,B,C,D]):
    print(f"{i} : {np.any(j,axis=0)}")

A : [False False False]
B : [False  True False]
C : [ True False False]
D : [ True False]


In [59]:
# 4. Question
# checking the array contains any NAN value in it.
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


In [60]:
# 5. checking the two array's are equal using 
# np.allclose(<var1>,<var2>) return true if a==b or else false.
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

print(np.allclose(A,B))

True


In [80]:
# 6 Question 
# "==" compares the elements of the two different array and produces the list in the form of list.
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
list_=[]
# my solution with , separated. and this wrong don't do this 
# for i,j in zip(A,B):
#     list_.append(i==j)
# print(list_)

# correct solution.
print(A==B)

[False False  True]


In [95]:
# 7.Question checking array A is greater than array B.
import numpy as np


A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
# my solution 
print(A>B)
# given solution .
print(np.greater(A, B))

[ True False False False]
[ True False False False]


In [116]:
# 8. Question
# creation of 4x4 matrix which has all the elements has 0's
# shape is used to define the order of the matrix.
# np.zeros() is used to create 0's in all the places of the elements
print(np.zeros(shape=(4,4),dtype='int'))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [122]:
# 10.Question
# creation of an array with same element.
# np.full() --> is used to apply the same element to all the position in the matrix.
# it has the element called fill_value --> used to assign the value which we are going 
#to fill in the matrix.


###           MY SOLUTION         ###
print(np.full(shape=(10,10),dtype='float',fill_value=255))

###          GIVEN SOLUTION       ###
# making a matrix with all one's 
# then multilying with the value you want fill.
print(np.ones(shape=(10,10),dtype='float')*255.)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]
[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255

In [125]:
import numpy as np

a = np.arange(10,100).reshape(9,10)

print(a)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
