In [8]:
#finding the determinant of the array 
import numpy as np

a=np.array([[12,4,4],[2,3,4],[1,4,6]])
print("the array is :",a)

#using the linalg.det funtion to find the determinant of the array a.

b=np.linalg.det(a)
print("the determinant of the array a is : ",b)

the array is : [[12  4  4]
 [ 2  3  4]
 [ 1  4  6]]
the determinant of the array a is :  12.000000000000027


In [12]:
#finding the inverse of the array 
import numpy as np

a=np.array([[12,4,4],[2,3,4],[12,3,4]])
print("the array is :",a)

#using linalg.inv function to find the inverse of the array a.

b=np.linalg.inv(a)
print("the inverse of the array a is : ",b)

the array is : [[12  4  4]
 [ 2  3  4]
 [12  3  4]]
the inverse of the array a is :  [[ 0.00000000e+00 -1.00000000e-01  1.00000000e-01]
 [ 1.00000000e+00 -3.17206578e-18 -1.00000000e+00]
 [-7.50000000e-01  3.00000000e-01  7.00000000e-01]]


In [16]:
#finding the norms 
import numpy as np

a=np.array([[12,4,4],[2,3,4],[1,4,6]])
print("the array is :",a)

#using linalg.norm to find the norm of the array a

b=np.linalg.norm(a,axis=1)
print("the norms of the array is : ",b)

the array is : [[12  4  4]
 [ 2  3  4]
 [ 1  4  6]]
the norms of the array is :  [13.26649916  5.38516481  7.28010989]


In [ ]:
#for further details in linear algebra use this link
#-->> ""https://numpy.org/doc/stable/reference/routines.linalg.html"" <<--
